travis:
  secure:
    BINSTAR_TOKEN: TqHZPZsxZbY1HkrXAbSb5q6mYh2KYxx689uoqZKJ08Ylthy5QvMUKtB9EaxBh447lSNiTrCDwlVuUl2WzNoo/p+7c4fHMlPFUQeyAO5xmKEWVN73hjX3BU35o807Xna6CJ5aIh0cUKAzM6a1NrlW7Rr9UxrpZEPK0WRfyxLabM9LqDmLARzxV8ukSpkfyCR5lf8JscCbOSgVkb6mbtqpXPki7qFi4RFJIrI0P5qUBHFi52ZITOZevVeDr65EnxEUKgNbi2ditSA3PKpGT+xg78GyvzHfreP8I/zZFltVPxuI0I67IAF1+M8q2gJDDUIddFwH3bD74n2NaRBIdmDw6hpuA9Gx7Ig/xa1xuPATc8bC8h9RMxxp4Jg1nd8B/INTGQFdhg4qb1oby9lO7s1qlmrJ+ANU+jTyd8mSuTAwEbokvmCdOzvCrF7FtSM/y1xfySnEqKj1ZGbdbFsSNHZUhxfaPiRWrXldUT1YbNSPxv/UjhR0cOr2HjRcgZ5iceE0zxFfCkvb0IkkJHIOLwn67LE/3ePwRtmfgw76FDTubI6g8vG5euAb4eAht1qNSu8IDhuOLqtudadfoT5CJ9koUzcx1nxsRbtRsWbSiLo4IbNPcsRRiH8ntZCyFjz0c0JLMUZi5BZdy0TXS2F12hHsiXkRN30lV5pbJxhnqhF0j1U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
