travis:
  secure:
    BINSTAR_TOKEN: Kq+gaNXNX5DtL/9d2r7Ou1yJ2n51VfMDRYfIoyZ9Jt6Or7qdjj4o0k0APTvrKonozFtdbDjFwPH7X2ckS1uh60y2eafBsiEgn0oi5SS4ijMrOsP/EHc9SOaMVgO1yJjju8xovlI4ohOn81LvVDceIqFMBuoGuNHWXD1PH2QWMf8tBrOGHholQ5dk6zyaKGGU482+SnVYnbLFIIdcSZUe9t/45/hyutdcQcwft9KZ0CEXricNIAV32itBQwARFajRy5O9lsF5YI7EynwUQPDxpg95B9RK6UZMRWhPWxGC3km3jrjU/I4RVJ3vBTwV36K02yBVCvolPKbDHy2XZlT5gUgcZvnikKMXpKahVXtYFE9p6WhJ1ig6JOYrZ7KI5xOMYTyOoJcwZHHPRgBh7AJEPiwpOZXp/1BYbjTp2Z/3VCy5nOjHmDJtJr7eJ4jyovRSKrtxB8X3CQdH4kOs5+a/KKi11C2FWr18QLhtlNSr8Pny+zPh1JhOWth4LBDv+NeR12s+sxa6SOzIHbq+8L4JPZa95vZ+x5hnaaLD84lquv7gCTd6RFtOrp9Pbg5qE72YLbTWcaEV/JJW54chB35MFDqfr5EhbABGnwLKcCzerdvVAa+sd65ZkymAVGs3AcBC03tCo1OKCWaLr2d2IYFWJoBUK/0u56KTgnoQ7y+cTt8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
