travis:
  secure:
    BINSTAR_TOKEN: G4UpWT1i5RmX5iqrkTEzwNwb7yE8mhv0t7knMMYv37EA1OWBU82hpHgVm0DDyz6EgJFGnzhu2HD1VF/6eOZVu0ecqdsraq12Q3373qJjcbqqjzRZ4qiUmJWc02L0JbgTFnmT9jeLf4U0QW5QUdKgefI7/drU6AnIvhaEZBBFhVaSAKVWMH91PjgW0AtYE9Ergu3bFV9XpKR36Y4yGZGscbVqHkYfj2J8OGMF6hvKBUAJRW2hDAB1UDLR6cV/aGvP5AhmUvFmISj7qyB1w6VEalYoU/XR11dgzK6k51P2iroxqCUZiz2Rm6zgTIMuzhyjGaMtezffMU7fKQRv2xrwnPEWGzR8ZlyvaD7KTNOBzKOfNOGjGNBsxzUfJssJXhlXQ9rAOl4Zz6oDaRUud+7zqLfUbPrBe/f2YhlVBaWOcbzuHfWjZxKjbGPiuniCyJy/LIqW1lBe6XSEqiJYiDt0IF0FxHDFyZs9yjbyJfr6HPYmN32doF1+/BiWJeGPaKWS0NnUuwLdp6bTocq/J6ulE0uFR8zegtc8320vDLYHDC86HdobHbxTSuFDFctGO+B+W+E8EgsFuE8eVdgypMGNQ7vipaVdL5MiTBvzvfrRrl/CMzxp3wrImdkLK2jX/tln+THrGkXJTySsR+YhFDs/vgLwy+H9YxpfJTK9BqFDqYA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
