appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bwvhtg0oxkhA77UGfz00ixIwwfeYVjApnDQNJ0ycOFHIX/x0adHdJwwmLouaKBXlcerRrv3ZeOqcEd/7/KbTFbQ5m6L2zFt4NOGC1Ndr/2oLbqgFK2WpDqMplNecVNN9Vz13rqqMC84Rcn1C3XXNyIjPHmoZ6NWF+AAgYb6TErsiLalmeGuvP77fWi+qz8UT35oJN1FjWGCGfsHaNowyizfnvxb3c+8t0NYQSuHBRBEiBFyiiDcmQLKWB+efqxgZLRZE1gLwHjWiPYfNQ8vXUfLij8yqOEXvfZAGeFvPmuINzw7noz027ptZYLieQMcvdfbG9n+9ikBiIZWxaZkXvsrr491MynEnFiccKlMjfkMvq9kIsOKzg54PSH7oORLLG9Le7jaJznOqdnBe1WehGUue8SzRLeBj7GJjtbrLC8C2qUQ0VQrC21soyEIPg2qEs+nxvcv8d8C8xS1ofBaj4oS4uC3Pq4cS5lLqiE5n89uy5wCNuOhuzZoiWcYIPmyq65oh5cjPY5MZpyljjKLJ4FQEigeSFp8q/xz9+pvUg/bTAUIMMpBnvr6T3T81rHK3U424vAOEWtpYS8I1Dakza+w94qxXvKIvHOJXU/5gyY0Hx7vLWVrx6tie6WKepJjgKo9Urnc5jpGDeurXcJCvbTkIA7gx4/kdOPPyw0HyFd4=}
