travis:
  secure:
    BINSTAR_TOKEN: X5HGiTgkavpQCZMkyd2O8hYz7G+0OHQPw8jVOMGAnAVrErG4l14VKSYRSIWtBpWwlhv0EwIE7MPnI0Ljz1wNF+ZL/u5UmqAY5GuSnsHeu+0ntUDvVUg3V0hG3/VKX8oM8G+RnKBohsoGosaIPDTaZSLZsRTfmoHUxlxrA6xHSrWvVqcpEe1EqfHxW3ZIMP8hvVeuAwxD92R6lZhQxh/XBzK48hSMV2/XnTY+BSDN7tDGn/pPDg2JyIzavvp0Eh2pnlA7fxEZFygy+DgVSLNJKfJozWJBBBaNJopHF8pVE7SrDDucu/2x5VRdDHEOo3BdijNmdJfLSFPfVvwJel31fvhWGQmuSMQWYUHjmCirWyrotdoBh64QObj7A9taVBvEpoS2VWxJB6TXd+jU0dMidkxm21FCn9vxyE5ogQIF3iyK+fgEPwuQKUAUDAdPBo3WhZXi8R0T8FVHrc6/g+6p1wGqqC50eW7IBLljpaBSk2ADd5AVN0pXhvipVnUxhBTRv4euxqBJc9Mzyk199OmRsV1rNgwi7sdxZmmS1jJHO/8JuQ1mHv9gCrXyZIQqnScSC34SpRXRWqIUC5u5RIAxPOrWujQ3liDPqxao/aqT/OBXb0dFyAA/lGX5MbFg8VUGYtk8PACPs2pAWfv5K9NQJovi2qeS2gH+Tnb7gwWdTV8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
